services:
#  api:
#    image: caronauff
#    build:
#      context: .
#      dockerfile: CaronaUFF.Api/Dockerfile
#    depends_on:
#      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:  
      MSSQL_SA_PASSWORD: "Carona2024!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./db-scripts/01-create-db-and-tables.sql:/tmp/01-create-db-and-tables.sql
      - ./db-scripts/02-initial-data.sql:/tmp/02-initial-data.sql
      - ./db-scripts/init-db.sh:/tmp/init-db.sh
    command: /bin/bash ./tmp/init-db.sh